
//importing dependencies
const express = require('express'); //requires the node.js express framework
const { execFile } = require('child_process'); //built in node.js tool to talk to the OS to launch and run a program
const path = require('path'); //handles universal pathing by making / and \ depending on the OS

const app = express(); //starts the node.js express framework
const port = 80; //defines the port to listen on

app.use(express.json()); //tells express to use a middleware to translate information between the backend and front end

app.use(express.static(path.join(__dirname, '../frontend'))); //tells express to look in the /frontend folder to find the webGUI

app.post('/api/evaluate', (req, res) => { //tels the server to listen for POST requests /api/evaluate is the endpoint and throws the req into it and response back
    const { expression, xMin, xMax, xCount } = req.body; //saves the body of the request containing the expression and graphing arguments

    if (!expression) { //error handling, if there is no expression then error 400
        return res.status(400).json({ error: "No expression provided" });
    }

    const binaryPath = path.join (__dirname, '../output/engine'); /*defines the binaryPath variable with path.join, which glues together the 
     __dirname which contains the location of the server.js file and uses ../ to go back one then output/engine to point at the binary */

     const args = [expression]; //creates an array with the raw math expression as the first input element

     if (expression.toLowerCase().includes('x')) { //checks if the incoming mathematical expression contains the variable letter x in upper or lowercase
        args.push(xMin || "0", xMax || "0", xCount || "0"); //pushes the graphing minimum maximum and point steps into the arguments list array
    }

    execFile(binaryPath, args, (error, stdout, stderr) => { /*this launches the engine binary and passes the expression directly to it and asynchronously waits
    for it to run and catches 3 things, any system errors, the standard output of the binary, and any standard errors with std::cerr */
        if (error) { //if the binary wasn't found or didnt launch
            return res.status(500).json({ //tells us the error code
                error: "Engine Execution Failed", //a message about what part failed
                details: stderr || error.message //gives us the details about what failed from std::cerr and the error message from here
            })
        }

        const points = []; //creates an empty array to store structured graphing points objects

        if (expression.toLowerCase().includes('x') && stdout) { //checks if the expression is a function graph and standard output contains data
            const lines = stdout.split('\n'); //splits the single text output block by newline characters into a manageable array of text lines
            for (const line of lines) { //loops through each individual line slice from the engine calculation log
                const match = line.match(/\(([^,]+),\s*([^)]+)\)/); //applies regular expressions to match and isolate digits inside coordinate parenthesis pairs
                if (match) { //if a valid coordinate format match is discovered on the active text track
                    points.push({ x: match[1].trim(), y: match[2].trim() }); //saves the cleaned x value string and y value string into the points registry array
                }
            }
        }

        return res.json({ //a successful json response
            success: true, //success is true
            input: expression, //contains the original math
            result: stdout, //contains the full raw result string from engine
            points: points.length > 0 ? points : null //contains the parsed array of coordinates if they were generated by the engine math
        })
    })
});

app.listen(port, () => {
    console.log(`Explicanda API Server running on http://localhost:${port}`)
})

